### ISSUE TITLE
conda has no win64 petsc4py

### ISSUE THREAD

**Issue by RichardScottOZ** [Geodels/gospl#268]
**To Reproduce**
Try installing environment yml in Windows 10

**Expected behavior**
Environment installed

**Screenshots**
```python
PackagesNotFoundError: The following packages are not available from current channels:
  - petsc4py
```
**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
- e.g. why I asked re: WSL etc.

**Comment by tristan-salles** [comment]
Yes petsc4py would need to be installed from `source` on windows which makes the process far from straightforward. As you suggested the best option would be to use WSL for windows machine...
