### ISSUE TITLE
AttributeError: 'icosahedral_mesh' object has no attribute 'lpoints'

### ISSUE THREAD

**Issue by RichardScottOZ** [Geodels/gospl#271]
**Describe the bug**

**To Reproduce**
Install an environment, try and run bfModel notebook

**Expected behavior**
runs

**Desktop (please complete the following information):**
 - OS: WSL

**Additional context**
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 18
     14     grid = stripy.spherical_meshes.octahedral_mesh(include_face_points=False, 
     15                                                    refinement_levels=ref_lvl)
     17 str_fmt = "{:25} {:9}"
---> 18 print(str_fmt.format('Number of points', grid.lpoints))
     19 print(str_fmt.format('Number of cells', grid.simplices.shape[0]))
     21 # Take the unit sphere mesh and assign the Earth radius to the coordinates

AttributeError: 'icosahedral_mesh' object has no attribute 'lpoints'
```

**Comment by RichardScottOZ** [comment]
that object has a points attribute?

In the bug template you can probably get rid of the 'mobile' section - is anyone running this on a mobile device?

**Comment by RichardScottOZ** [comment]
presuming this is npoints?

**Comment by RichardScottOZ** [comment]
these couple of syntax things - see pull request

**Comment by tristan-salles** [comment]
Here again this is an issue related to changes in `stripy` library. I am now defaulting to [jigsaw](https://github.com/dengwirda/jigsaw-geo-python) and will make some examples available soon!
