### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'platedata' with no tectonic data inputted

### ISSUE THREAD

**Issue by abdulrabiu** [Geodels/gospl#291]
**Describe the bug**
AttributeError: 'Model' object has no attribute 'platedata' despite not having inserted any plate or tectonic data into the model in the first place.

**To Reproduce**
1. Set up docker container with jupyter
2. Set up input.yml (without tectonic or precipitation data)
3. Run erosion.ipynb
4. See error relating to tectonic data (?)

**Expected behavior**
No error considering there is no tectonic data inputted

**Screenshots**
From input.yml:
![image](https://github.com/user-attachments/assets/dbd56529-8a1f-41b1-8dba-56436dd171a5)

From erosion.ipynb:
![image](https://github.com/user-attachments/assets/b431b88c-2dff-47c2-a953-9edac39dd8b1)
![image](https://github.com/user-attachments/assets/53d2572d-180a-4f6f-85da-9848d6ad9939)
![image](https://github.com/user-attachments/assets/19c9763f-2f46-4275-b7cd-00ca3745c194)
![image](https://github.com/user-attachments/assets/1d04b0ac-fc69-48a5-9487-a215e79d45f4)
![image](https://github.com/user-attachments/assets/216e0aa4-2dcf-44f9-bdf9-4ab45c481762)

**Desktop:**
 - OS: Windows 11 WSL
 - Browser: Firefox
 - Version: gospl v1.1.2

**Additional context**
This is all from [worldbuildingpasta's tutorial](https://worldbuildingpasta.blogspot.com/2023/03/an-apple-pie-from-scratch-part-viic.html#usinggospl) on the matter, in case reference is necessary.

**Comment by abdulrabiu** [comment]
Forgot to add this screenshot of a separate error, no clue if its related or not:
![image](https://github.com/user-attachments/assets/fb44ba6d-369a-4f67-832e-f58b748c2dbb)

**Comment by tristan-salles** [comment]
Sorry for the late reply, a new version of goSPL has just been released with a series of **[examples](https://github.com/Geodels/goSPL-examples)**.

For installing the newest version of goSPL and to run the examples the easiest way will be to use our Docker [container](https://hub.docker.com/r/geodels/gospl) or to follow the instructions for [Conda](https://gospl.readthedocs.io/en/latest/getting_started/installConda.html#building-gospl-full-stack-environment).
