### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ininja-ininja** [Geodels/gospl#292]
When I follow your tutorial this command won't work. Am I doing something wrong?
![Screenshot 2024-08-02 043216](https://github.com/user-attachments/assets/75ceb08a-73f0-4d8f-99a9-96dfd576f7e3)

**Comment by tristan-salles** [comment]
Sorry for the late reply, a new version of goSPL has just been released with a series of **[examples](https://github.com/Geodels/goSPL-examples)**.

For installing the newest version of goSPL and to run the examples the easiest way will be to use our Docker [container](https://hub.docker.com/r/geodels/gospl) or to follow the instructions for [Conda](https://gospl.readthedocs.io/en/latest/getting_started/installConda.html#building-gospl-full-stack-environment). 

In your specific case as you are using Windows you might want to upload and open it via the Docker [Dashboard](https://gospl.readthedocs.io/en/latest/getting_started/installDocker.html#docker-dashboard).
