### ISSUE TITLE
technical guide : description of plate tectonics?

### ISSUE THREAD

**Issue by johnjarmitage** [Geodels/gospl#94]
As part of the JOSS review (https://github.com/openjournals/joss-reviews/issues/2804), I am thinking that a description of how plate tectonics is included might be a great addition to the page https://gospl.readthedocs.io/en/latest/tech_guide/index.html#tech-guide. The erosion, deposition, and compaction algorithms are described, but I don't see a description of the methods used to:
* laterally move the surfaces (gplates?)
* remesh if needed, as the grids get distorted
* deal with the collision of sediments (I assume there is no actual compression of sediment and crust, but something must be done at the plate boundaries, right?)

Or if all of the above is wrong, then maybe some text explaining what is done, because it is possible I am assuming a complexity that does not exist.

**Comment by tristan-salles** [comment]
Following @johnjarmitage suggestion I have added a description of how tectonic displacements are accounted for in the code: https://gospl.readthedocs.io/en/latest/tech_guide/tecto.html

**Comment by johnjarmitage** [comment]
Thanks for adding the description. I have one question after reading the description for the horizontal advection: What do you do in regions of diverging or converging latteral movement? Is the elevation interpolated from the last time step, and then uplift/subsidence is addded if there is any? In this sense the vertical and horizontal movement of the surface is applied *kinematically* (if this is the right word?) at each time step, and then erosion and deposition occur leading to an update in the surface elevation?

**Comment by tristan-salles** [comment]
That's right, I have added it in the tectonic forcing description in the technical guide.

**Comment by johnjarmitage** [comment]
Great. I understand it now. I'll close this issue.

**Comment by kbarnhart** [comment]
@tristan-salles quick comment to say that the tectonic forcing description is very nice!
